import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getBeatDetail, getErrorMessage } from '../services/api.js';
import PageContainer from '../components/PageContainer.jsx';
import Card from '../components/Card.jsx';
import ClassBadge from '../components/ClassBadge.jsx';
import LoadingState from '../components/LoadingState.jsx';
import ErrorState from '../components/ErrorState.jsx';

export default function PredictionConfidence() {
  const { recordId, beatIndex } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let active = true;
    setLoading(true);
    getBeatDetail(recordId, beatIndex)
      .then((res) => {
        if (active) {
          setData(res);
          setError(null);
        }
      })
      .catch((err) => {
        if (active) setError(getErrorMessage(err));
      })
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => { active = false; };
  }, [recordId, beatIndex]);

  if (loading) return <LoadingState label="Computing prediction probabilities and confidence breakdown…" />;
  if (error) return <ErrorState message={error} onRetry={() => window.location.reload()} />;

  const probs = data?.probabilities || { N: 0, S: 0, V: 0, F: 0 };
  const isEdge = data?.is_edge_beat;

  return (
    <PageContainer
      title={`Prediction & Confidence — Beat #${beatIndex}`}
      subtitle={`Posterior probability distribution across the 4-class ANSI/AAMI diagnostic taxonomy generated by the frozen Random Forest model.`}
      breadcrumbs={
        <>
          <Link to="/records">Records</Link>
          <span>/</span>
          <Link to={`/analysis/${recordId}`}>Record {recordId}</Link>
          <span>/</span>
          <Link to={`/beat/${recordId}/${beatIndex}`}>Beat {beatIndex}</Link>
          <span>/</span>
          <span>Prediction</span>
        </>
      }
      actions={
        <Link to={`/beat/${recordId}/${beatIndex}`} className="btn btn-secondary btn-sm">
          Inspect Beat Morphology
        </Link>
      }
    >
      <Card title="Classification Decision Summary">
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
          <div>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Assigned Class: </span>
            <ClassBadge cls={data?.predicted_class} showDescription size="lg" />
          </div>

          <div>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Model Confidence: </span>
            <span className="font-mono" style={{ fontSize: '1.2rem', fontWeight: 800, color: 'var(--accent-cyan)' }}>
              {isEdge ? 'N/A (Edge Beat)' : `${((data?.confidence || 0) * 100).toFixed(1)}%`}
            </span>
          </div>
        </div>
      </Card>

      {/* 4-Class Probability Distribution */}
      <Card
        title="Class Probability Distribution"
        subtitle="Normalized ensemble vote proportions across 200 decision trees."
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {[
            { key: 'N', label: 'Normal / Bundle Branch Block', val: probs.N, color: 'var(--color-class-N)' },
            { key: 'S', label: 'Supraventricular Ectopic (SVEB)', val: probs.S, color: 'var(--color-class-S)' },
            { key: 'V', label: 'Premature Ventricular Contraction (VEB)', val: probs.V, color: 'var(--color-class-V)' },
            { key: 'F', label: 'Fusion Beat', val: probs.F, color: 'var(--color-class-F)' },
          ].map((item) => (
            <div key={item.key} style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.88rem' }}>
                <span style={{ fontWeight: 600 }}>
                  <span style={{ color: item.color, marginRight: '0.5rem' }}>●</span>
                  Class {item.key}: {item.label}
                </span>
                <span className="font-mono" style={{ fontWeight: 700, color: item.color }}>
                  {(item.val * 100).toFixed(2)}%
                </span>
              </div>
              <div
                style={{
                  height: '10px',
                  backgroundColor: 'var(--bg-surface-2)',
                  borderRadius: 'var(--radius-full)',
                  overflow: 'hidden',
                }}
              >
                <div
                  style={{
                    height: '100%',
                    width: `${Math.min(100, Math.max(0, item.val * 100))}%`,
                    backgroundColor: item.color,
                    borderRadius: 'var(--radius-full)',
                    transition: 'width 0.3s ease',
                  }}
                />
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Phase 20 Preview Banner */}
      <div className="phase-banner">
        <h3 className="phase-banner-title">Phase 20 Preview: Decision Boundary Explorer</h3>
        <p className="phase-banner-desc">
          Ensemble tree variance, entropy-based uncertainty quantification, and per-tree vote visualizer will be released in Phase 20.
        </p>
        <Link to={`/analysis/${recordId}`} className="btn btn-outline btn-sm">
          Return to Record Overview
        </Link>
      </div>
    </PageContainer>
  );
}
